#Settings
title: Easy Roleplay
email: contact@benbuckton.com
description: "Straight forward set of prinatables so you can start roleplaying in the next 15 minutes"
url: "https://easyroleplay.com"

partials:
  - "_includes"
  - "sections"
