const NpcNames = {
    "greekMan":   ["Abantes","Abas","Abascantus","Abderos","Aberkios","Ablerus","Abreas","Abronychus","Abydos","Acaeus","Acamus","Acessamenus","Acestes","Aclepiades","Acrisias","Acrisius","Acroneos","Actor","Adeimanthos","Adelphius","Admetos","Adrastos","Adrastus","Adrestus","Aeaces","Aegaeon","Aegicoros","Aegisthes","Aegon","Aeimnestos","Aenesidemos","Aeolus","Aeropus","Aeschreas","Aesculapius","Aesepus","Aeson","Aesop","Aetes","Aethon","Aetion","Aetios","Aetolos","Agamedes","Agamemnon","Agapenor","Agapias","Agastrophos","Agathocles","Agathon","Agelaus","Agenor","Agesilaus","Agetos","Agis","Agrias","Aiantes","Aias","Aigeus","Airopos","Aischylos","Akadios","Akamas","Aktis","Aktor","Alastor","Alcaeos","Alcandros","Alcides","Alcimos","Alcinous","Alcmaion","Alcman","Alcon","Alector","Alektryon","Aleuas","Alexandros","Alexarchos","Alexias","Alexis","Alexon","Alkamenos","Alkestis","Alketas","Alkibiades","Alkides","Alkimachos","Alkiphron","Alkmaion","Aloeus","Alphaeus","Alpheos","Alphesiboeus","Alphios","Altes","Alypius","Amarinceus","Ameinias","Ameinokles","Amiantos","Amompharetos","Amopaon","Amphiaraos","Amphidamos","Amphimachos","Amphimnestus","Amphinomous","Amphion","Amphios","Amphitrion","Amyntas","Amyntor","Amyris","Amythaon","Anabesineos","Anacharsis","Anakletos","Anakreon","Anastasios","Anaxagoras","Anaxandridas","Anaxandrides","Anaxandros","Anaxarchos","Anaxilaus","Anaximander","Anaximenes","Anaxis","Anaxos","Anchialus","Anchimolios","Anchises","Ancus","Andokides","Andraemon","Andreas","Androbulos","Androcles","Androdamos","Androgeus","Aneristos","Aniketos","Anisodoros","Antaeus","Antagoras","Antemion","Antenor","Anthemion","Antichares","Antidoros","Antigenes","Antigonos","Antikles","Antilochus","Antinous","Antiochus","Antipatris","Antipatros","Antiphales","Antiphones","Antiphus","Antisthenes","Anytos","Anytus","Apelles","Apellicon","Aphidnos","Apisaon","Apollodoros","Apollophanes","Apollos","Aratus","Arcas","Arcesilaus","Archagoras","Archelaos","Archeptolemus","Archesilaus","Archestratidas","Archilochus","Archytas","Arcidamus","Arcturus","Areilycus","Areisius","Areithous","Argades","Argaeus","Argos","Aridolis","Arion","Ariphron","Aristaeus","Aristagoras","Aristaios","Aristandros","Aristarchos","Aristarchus","Aristides","Aristion","Aristippus","Aristoboulos","Aristobulus","Aristocles","Aristocypros","Aristodemos","Aristogeiton","Aristomachos","Ariston","Aristonous","Aristonymos","Aristophanes","Aristophantes","Aristos","Aristotles","Aristoxenus","Arrabaios","Arridaios","Arsenios","Artemas","Artemidoros","Artemios","Artemisthenes","Arybbas","Asasthenes","Ascalaphus","Ascanius","Aschines","Asius","Asklepios","Asonides","Asopodoros","Asopus","Asphalion","Assaraeus","Astacos","Aster","Asterion","Asteropaeus","Astrabacus","Astyanax","Athamas","Athenades","Athenaeus","Athenion","Athenodorus","Atiphates","Atreus","Atrometos","Attaginas","Attaginos","Attalos","Atymnius","Atys","Audax","Augias","Auletes","Autesion","Autodikos","Autolycus","Autolykos","Automedon","Autonous","Axylus","Azeus","Bacchides","Bacchios","Bacchylides","Bacenor","Bacis","Baerius","Balius","Barates","Bardas","Basileides","Basileios","Basilides","Bathyaes","Belos","Bendis","Bianor","Bias","Bion","Bisaltes","Biton","Blathyllos","Boethus","Borus","Boter","Briareus","Briarus","Brison","Brygos","Bucoli","Bulis","Burrhus","Butacidas","Cöon","Callimachus","Callimorphus","Carenos","Carneades","Carpophorus","Carpus","Casambus","Castor","Ceas","Cebriones","Celeas","Cephalos","Cepheus","Cephissos","Ceyx","Chabrias","Chaeremon","Chairophon","Chalcodon","Chalcon","Charax","Chares","Charidemos","Charilaus","Charillos","Charmides","Charon","Charopos","Cheiron","Chersis","Chileos","Chilon","Choerilos","Choeros","Chremes","Chremon","Chremonides","Chromis","Chromius","Chrysaor","Chryses","Chrysippos","Chrysogones","Chrysogonus","Chrysolorus","Cilix","Cineas","Cinyras","Cisses","Cisseus","Cleades","Cleandros","Cleathes","Cleisthenes","Cleobulus","Cleodaeos","Cleombrotos","Cleomenes","Cleon","Cleonicus","Cleonymus","Clinias","Clisthenes","Clonius","Clytius","Clytomedes","Cnoethos","Cobon","Codros","Coenus","Coeranus","Coes","Cois","Conon","Copreus","Cordylion","Coronos","Corydallos","Corydon","Crathis","Cratinus","Cratippus","Cretheus","Crethon","Cretines","Crios","Croesus","Cronos","Cteatus","Ctesippus","Cuphagoras","Cyberniskos","Cycnus","Cylon","Cynaegiros","Cyncus","Cyneas","Cyniscus","Cypselos","Cyrenios","Cytorissos","Dadaces","Daedalos","Daetor","Damasippus","Damasithymos","Damasos","Damastor","Damian","Damianos","Damiskos","Damoetas","Damon","Danaos","Danaus","Daphis","Daphnis","Dardanus","Dares","Davos","Deinias","Deinokrates","Deinomenes","Deiotones","Deiphobus","Deiphonous","Deipylus","Demades","Demaratos","Demarmenos","Demas","Demeas","Demetrios","Democedes","Democoön","Demodocus","Demokrates","Demoleon","Demonax","Demonous","Demophlos","Demosthenes","Deon","Derkylos","Deukalion","Dexicos","Dexios","Diactorides","Diadromes","Diadumenus","Diagoras","Dicaeus","Dieneces","Diocles","Diodoros","Diodorus","Diokles","Diomedes","Dionysios","Dionysophanes","Dionysos","Diophantus","Diores","Dioscuros","Diotrephes","Dismas","Dithyrambos","Dmetor","Dolon","Dolops","Doreios","Doreius","Dorian","Doriskos","Doros","Dorotheus","Doryssos","Dosithios","Drimylos","Dromeus","Dryas","Dryops","Ducetius","Duris","Dymas","Dymnos","Echëeus","Echekrates","Echelaos","Echemmon","Echemus","Echephron","Echepolus","Echestratos","Eetion","Eioneus","Eirenaios","Elasus","Elatos","Elatreus","Eleon","Elephenor","Elpenor","Elpides","Elpidius","Empedocles","Endios","Endymion","Engenes","Eniopus","Ennaeus","Ennomus","Ennychus","Enops","Eos","Epaenetus","Epaphos","Epaphroditus","Epeigeus","Epeius","Ephialtes","Epicurus","Epicydes","Epikrates","Epimenes","Epiphanes","Epistor","Epistrophos","Epitrophos","Epizelos","Erasistratus","Eratosthenes","Eratostheres","Erechtheus","Eretmenus","Ereuthalion","Erginus","Ergiyios","Erichthonius","Erxandros","Eryalus","Erysichton","Eryx","Eryximachos","Eteocles","Eteokles","Eteonous","Euaemon","Eualcidas","Euanthes","Euarestos","Eubalus","Eubulus","Eucarpus","Euchenor","Eucleides","Eudorus","Eudoxsus","Eudoxus","Euenius","Euenor","Euenus","Eugammon","Eugenios","Eugenius","Euhemenis","Euippus","Eukles","Eumaeus","Eumastas","Eumelus","Eumenes","Eumneus","Eumolpus","Euneas","Euonomos","Eupalinus","Euphenes","Euphorbos","Euphorion","Euphronios","Eupolos","Euripides","Euryanax","Eurybates","Eurybiades","Eurycliedes","Eurydamus","Eurydemon","Eurydemos","Euryhus","Eurykrates","Eurykratides","Euryleon","Eurylochos","Eurymachos","Euryphon","Eurypylos","Eurystenes","Eurysthenes","Eurystheus","Eurysthios","Eurythion","Eurytos","Eussorus","Euthydemos","Euthynos","Eutropios","Eutuches","Eutychides","Eutychus","Evaenetos","Evagoras","Evandros","Evanetus","Evelthon","Evenios","Evenus","Evios","Exaduis","Exekias","Faenus","Galenus","Gallus","Ganymedes","Gauanes","Geleon","Gelo","Gelon","Gennadios","Gerasimos","Giorgius","Glaukias","Glaukos","Glycon","Gnipho","Gordias","Gorgias","Gorgion","Gorgos","Gorgythion","Gregorius","Gryllus","Gurgos","Gylippos","Gyras","Gyrtias","Haemon","Hagias","Hagnon","Halisthertes","Halius","Harmatidas","Harmocydes","Harmodios","Harmon","Harpagos","Harpalion","Harpalos","Harpocras","Hecataeus","Hegesandros","Hegesistratos","Hegetoridas","Heirax","Heiron","Hektor","Helenos","Helgesippos","Helicaon","Heliodorus","Helios","Helle","Hephaestos","Herakleides","Herakleitos","Heraklides","Hermeias","Hermeros","Hermippos","Hermogenes","Hermolaos","Hermolycus","Hermon","Hermotimos","Hero","Herodes","Herodianus","Herodion","Heromenes","Hicetaon","Hiero","Hieronymus","Hipparchos","Hipparinos","Hippasus","Hippias","Hippocoön","Hippoklides","Hippokratides","Hippolytos","Hippomachos","Hippomenes","Hippon","Hipponax","Hipponicus","Hipponous","Hippotas","Hippothous","Hippotion","Hoiples","Homeros","Hyakinthos","Hylas","Hyllos","Hyllus","Hypatius","Hypeirochus","Hypenor","Hyperenor","Hyperion","Hypsenor","Hyrcanus","Hyrtacus","Hyrtius","Iakchos","Ialmenes","Iambulus","Iamus","Iasos","Iatragoras","Iatrokles","Ibanolis","Ibykos","Icarion","Icarius","Icarus","Idaeus","Idaios","Idas","Idomeneus","Ilioneus","Illyrius","Ilus","Imbrasus","Imbrius","Imbrus","Inachos","Inachus","Inaros","Iobates","Iolaos","Iollas","Ion","Iphiclus","Iphicrates","Iphikrates","Iphinous","Iphitos","Iphitus","Iros","Irus","Isagoras","Isandros","Ischenous","Isidor","Isidoros","Ision","Ismaros","Ismenios","Isocrates","Isodemos","Isokrates","Itheus","Itylus","Itys","Kadmos","Kaenas","Kaeneus","Kalchas","Kalesius","Kaletor","Kalliaros","Kallias","Kallikles","Kallikrates","Kallimachos","Kallinicus","Kallinos","Kallipides","Kallipos","Kallisthenes","Kallon","Kameirus","Kandaules","Kannadis","Kapaneus","Kapys","Karipos","Karopophores","Kasos","Kassandros","Kaunos","Kebalinos","Kebes","Kekrops","Keos","Kephalon","Kephalos","Kerameikos","Kerkyon","Keteus","Kimon","Kirphis","Kittos","Kleitos","Kleobis","Kleomenes","Koines","Koinos","Konon","Koragos","Korax","Kosmas","Krantor","Krateros","Kreon","Krinippos","Kristos","Kritias","Kritoboulos","Kritodemos","Kriton","Kroisos","Krokinos","Ktesiphon","Kyknos","Kynaegeiros","Kyrillos","Kyrios","Kyros","Labdacus","Labotas","Laertes","Lagos","Laios","Lamachos","Lampo","Lampon","Lampus","Lamus","Laodamas","Laodocus","Laogonus","Laomedon","Laphanes","Lasos","Lasthenes","Laureion","Leagros","Leandros","Learchos","Leicritus","Leitus","Lemnus","Leo","Leocedes","Leodes","Leon","Leonidas","Leonnatos","Leontiades","Leontis","Leoprepes","Leotychides","Lethos","Leucippus","Leukos","Lichas","Licymnios","Linus","Loxias","Lukos","Lycaon","Lycaretos","Lycidas","Lycomedes","Lycophon","Lycophron","Lycoris","Lycurgos","Lycus","Lydus","Lygdamis","Lykomedes","Lykon","Lynceus","Lysagoras","Lysandros","Lysanios","Lysias","Lysikles","Lysimachos","Lysippos","Lysippus","Lysis","Macar","Macarias","Machaon","Maeon","Maiandrios","Makarios","Maleos","Males","Mantes","Mantios","Marcion","Marnes","Maro","Maron","Marsyas","Mastor","Matullus","Mausolos","Mecistes","Mecistios","Medios","Medon","Medus","Megadates","Megakles","Megakreon","Megapenthes","Megareus","Megasthenes","Megathenes","Meges","Megistias","Meidias","Melampos","Melampus","Melanippos","Melanthios","Melanthos","Melas","Meleagros","Melegros","Meles","Meliboeus","Melicertes","Memnon","Menalcas","Menandros","Menares","Menekrates","Menelaos","Menestas","Menesthes","Menesthios","Menexinos","Menoeces","Menoitios","Mentes","Mentor","Meriones","Mermerus","Merops","Mesaulius","Mesthles","Methodios","Metiochus","Meton","Metrobius","Metron","Metrophanes","Meurius","Micythos","Midas","Midylos","Mikkos","Mikon","Milanion","Miltiades","Minos","Misenus","Mnasyllus","Mnesiphilos","Mnester","Mnesus","Moeris","Moliones","Molpagoras","Monoecus","Monomachus","Mopsius","Mopsus","Morsimus","Morys","Moschion","Mulius","Musaeus","Musaios","Mydon","Mygdon","Myrsinus","Myrto","Mys","Narkissos","Nastes","Naubolus","Naukles","Nausithous","Nauteus","Nearchos","Neleos","Nelpus","Neokles","Neoptolemos","Neritos","Nestor","Niarchos","Nicandros","Nicanor","Nicholas","Nicholaus","Nicias","Nicodromos","Nicolaus","Nicomachos","Nicon","Nikandros","Nikanor","Nikasios","Nikeratos","Nikias","Nikomachos","Nikomedes","Nilus","Nireus","Nisos","Noemon","Nomion","Nothon","Numa","Nyctinus","Nymphicus","Nymphodorus","Ocealus","Ochesius","Ochos","Ocytos","Odaenathus","Odius","Odysseus","Oeagnus","Oecleus","Oedipus","Oenemaus","Oeneus","Oenomaus","Oenopion","Oenops","Oicles","Oileas","Oliatos","Olus","Olympicus","Olympiodorus","Onamakritos","Onesilos","Onesimos","Onesiphorus","Onetas","Onetor","Onias","Onomastos","Ophelestes","Opites","Ops","Orcus","Orestes","Oresus","Orges","Oribasius","Orion","Orius","Oroites","Orpheus","Orsilochus","Orsiphantes","Orthaeus","Orythroneus","Otreus","Otrynteus","Otus","Paeëon","Paios","Palaechthon","Palaemon","Pallans","Pallas","Palmys","Pammon","Panaetios","Panaetius","Panares","Pandaros","Pandion","Panionos","Panites","Pankratios","Pantares","Panthous","Pantites","Paopeus","Paraebates","Paris","Parmenides","Parmenion","Parthenopaeus","Pasion","Pataicos","Patrobas","Patrobus","Patroclus","Patron","Pausanius","Pedaeus","Pedasus","Pedocles","Peirithous","Peiros","Peisandros","Peithon","Pelagon","Pelegon","Peleus","Pelias","Pelicles","Pelonus","Pelopidas","Peneleos","Peneus","Pentheus","Penthylos","Peolpidas","Perdikkas","Perdix","Periandros","Periclymenus","Perieeres","Perikles","Perimedes","Perimos","Periphas","Periphetes","Periscus","Peritas","Periumus","Peteos","Peukestes","Phaedo","Phaenippos","Phaeops","Phaestus","Phaidon","Phaidriades","Phalanthus","Phalces","Phalinos","Phanagoras","Phancis","Phanes","Phanias","Phantias","Pharnaces","Phausius","Phegeus","Pheidias","Pheidippides","Pheidon","Phemius","Phereclus","Pherecydes","Pheres","Pheronactus","Phidias","Phigaleios","Philagros","Philaon","Phileas","Philemon","Philetor","Philiskos","Philistos","Phillipos","Philocion","Philocrates","Philoctetes","Philocypros","Philoetius","Philogus","Philokles","Philokrates","Philolaos","Philologus","Philomen","Philomenes","Philometer","Philon","Philonikos","Philopoemon","Philostratos","Philostratus","Philotas","Philotectes","Philoxenos","Philpoemon","Phineus","Phintias","Phlaris","Phlegon","Phlios","Phoenix","Phoibus","Phoinix","Phoitios","Phokas","Phokion","Phorbas","Phorcys","Phormion","Phormos","Photius","Phrixus","Phrynichos","Phrynikos","Phrynon","Phylacus","Phylas","Pidytes","Pigres","Pinder","Pirithoos","Pisistratos","Pistias","Pittacos","Pittacus","Pittheus","Pixodarus","Plades","Pleistarchos","Pleistos","Plutarch","Podaeleirus","Podaleirus","Podalinus","Podarces","Podargos","Podaroes","Podes","Poeas","Poecas","Poimen","Polemion","Poliadas","Pollio","Polyas","Polybius","Polyctor","Polydectes","Polydeuces","Polydius","Polydoros","Polyeides","Polygonus","Polykleitos","Polykles","Polykritos","Polymedes","Polyneices","Polypemon","Polyperchon","Polyphemous","Polyphetes","Polyphontes","Polypoetes","Polyxeinus","Ponteus","Porphyrios","Porphyrius","Poseidon","Posides","Posidonios","Potamon","Pratinos","Praxilaus","Praxis","Praxiteles","Praxites","Prexinos","Priam","Prinetadas","Priskos","Procrustes","Proctus","Proetus","Prokles","Prokopios","Prokrustes","Proreus","Protagoras","Protesilaus","Prothoenor","Prothous","Protogenes","Protus","Proxenos","Prymneus","Prytanis","Ptolemaios","Ptolomaeus","Pylades","Pylaemenes","Pylaeus","Pylartes","Pylas","Pylenor","Pyris","Pyrrhus","Pythagoras","Pytheas","Pythes","Pythios","Pythogenes","Radamanthos","Rhadamanthos","Rhesus","Rhexenor","Ribes","Rizon","Sabas","Sabyllos","Salmoneus","Sarpedon","Satyros","Scaios","Scamandius","Scamandrius","Schedius","Scylax","Scyllias","Scythas","Sebastos","Seisames","Selagus","Seldomus","Selepos","Seleukos","Sicinnos","Siculus","Silanos","Silenos","Simmias","Simo","Simoisius","Simonides","Sinis","Sinon","Sippas","Siromos","Sisyphus","Skiron","Smindyrides","Smintheus","Socus","Sophanes","Sophokles","Soranus","Sosibios","Sosicles","Sosigines","Sosilus","Sosimenes","Sosipatros","Sosthenes","Sostias","Sostratos","Spertias","Speudon","Speusippos","Spinther","Spirodion","Stachys","Stentor","Stesagoras","Stesanor","Stesilaus","Sthenelaus","Sthenelus","Stichius","Stolos","Strabo","Strachys","Stratios","Straton","Strophantes","Strophius","Strymon","Syagros","Syennesis","Syloson","Synesius","Talaemenes","Talaos","Talaus","Talos","Talthybios","Tarchon","Taureas","Tebaeus","Tecton","Teiresias","Telamon","Telekles","Telemacho","Telemachos","Telemachus","Telephos","Telephus","Telesinus","Telesphorus","Telines","Tellias","Tellis","Telys","Temenos","Tenes","Tenthredon","Tereus","Terillos","Teucer","Teukros","Teutamos","Teuthranes","Teuthras","Thales","Thalpius","Thalysios","Tharybis","Thaulos","Thaumastus","Theagenes","Theages","Theas","Theasides","Themistius","Theoclymnius","Theocydes","Theodekles","Theodoros","Theodotus","Theognis","Theomestor","Theomestros","Theophanes","Theophrastos","Theophrastus","Theophylaktos","Theopompos","Theopompus","Theopropides","Theoros","Theos","Theramenes","Therapon","Theras","Thero","Theron","Thersandros","Therseandros","Thersilochus","Thersites","Thessalos","Thestor","Thettalos","Thoön","Thoas","Thon","Thorax","Thrasidaios","Thrasilaus","Thrasius","Thrasybulos","Thrasyllus","Thrasymedes","Threspotus","Thukydides","Thyestes","Thymoetes","Thymotes","Thyrsis","Thyrsos","Timagenidas","Timagoras","Timais","Timanthes","Timasion","Timasitheus","Timesithius","Timnes","Timoleon","Timon","Timonax","Timotheus","Timoxenos","Tiro","Tirynthius","Tisamenos","Tisandros","Tisias","Tithonius","Titormos","Tityrus","Tlepolemus","Tmolus","Trechus","Triopas","Triptolemus","Triton","Troezenus","Trophimus","Trophnus","Tros","Trypho","Turrianus","Tychaeus","Tydeides","Tydeus","Tymnes","Tyndareus","Tyndarios","Ucalegon","Vettias","Xanthippos","Xanthippus","Xanthos","Xenagoras","Xenokrates","Xenophanes","Xenophon","Xiphilinus","Xuthos","Xuthus","Zagreus","Zamolxis","Zenicetes","Zenodoros","Zephyrinus","Zethus","Zeuxidamos","Zeuxis","Zosimus"],
    "greekWoman": ["Achaia","Achradina","Actaëe","Actë","Ada","Adeia","Aedon","Aegiolea","Aegle","Aerope","Aethre","Agamede","Aganippe","Agape","Agapia","Agarista","Agathé","Agathonice","Agave","Aglaia","Aglaurus","Aikaterine","Aithra","Aketa","Alcandre","Alcestis","Alcippe","Alcmene","Alcyone","Alemene","Alkmena","Althaea","Althaia","Althea","Amarhyllis","Amathea","Amatheia","Amphithoe","Amphitrite","Ampinomene","Amplias","Anais","Anastasia","Andromeda","Antehe","Anteia","Antheia","Anthousa","Anthusa","Anticleia","Antigone","Antiochis","Antiope","Anysia","Appollonia","Apseudes","Arete","Arethusa","Argeia","Ariadne","Arisbe","Aristonike","Aristophane","Arsinoe","Artemidora","Artemisia","Aspasia","Astera","Astyoche","Astyocheia","Atalanta","Atë","Athis","Auge","Augo","Autonoe","Auxesia","Axiothea","Barbara","Basiane","Baucis","Berenike","Bito","Briseis","Caenis","Caleope","Callianeira","Callianessa","Calliphana","Calypso","Canace","Castianiera","Charis","Chione","Chiore","Chloë","Chloris","Chryse","Chryseis","Chrysothemis","Cilissa","Cilla","Circe","Clio","Clymene","Clymere","Colubra","Corythia","Cratais","Creusa","Crisa","Ctimene","Cybele","Cydippe","Cymodoce","Cymothoe","Cyrene","Cythereia","Cytheris","Damaris","Damia","Danaë","Deianeira","Deineira","Deiphobe","Deipyle","Delias","Demetria","Demophile","Dexamene","Dianeme","Diomede","Dione","Dirce","Doris","Dorothea","Doto","Drosis","Dynamene","Egeria","Egina","Eidothee","Eileithyia","Elcmene","Electra","Elpir","Endeis","Enyo","Eos","Epicaste","Eriboea","Erigone","Eriopis","Eriphyle","Eris","Eucarpia","Eudokia","Eunice","Euodias","Euphro","Euphrosyne","Europa","Eurycleia","Eurydike","Eurynome","Evadne","Galatea","Glauce","Glyke","Gorgo","Gygaea","Haidee","Halie","Harmodias","Harmonia","Hecuba","Hekabe","Hekaline","Hekate","Helice","Helike","Heliodora","Hellanike","Helle","Hermine","Hermione","Hero","Herophile","Hesione","Hilaera","Hippodameia","Hippodamia","Hippolyta","Hypsipyle","Hyrmina","Iaera","Ianeira","Ianessa","Ianthe","Ino","Iola","Iolanthe","Iole","Iomene","Ione","Iphianassa","Iphigenia","Iphimedeia","Iphis","Iphitheme","Irene","Iris","Isadora","Ismene","Issa","Jocasta","Kallisto","Kallixeina","Kassandra","Katana","Katina","Kephissa","Kharmion","Khlöe","Khloris","Kleio","Kleopatra","Klymene","Klytemnestra","Koré","Koritto","Kydilla","Kynna","Kynthia","Kypris","Kyra","Labda","Lais","Lalage","Lampetie","Lampito","Lanike","Laodameia","Laodamia","Laodice","Laothoe","Lasthena","Latona","Leda","Lede","Leto","Leucothea","Leucothoë","Limnoreia","Lois","Lyra","Maeonia","Maera","Maia","Maiandria","Marpessa","Medea","Medesicaste","Megaera","Megara","Megare","Melanie","Melantho","Melissa","Melita","Melite","Menelaia","Merope","Metis","Metriche","Milo","Milto","Molpadia","Monima","Monime","Mykale","Myrine","Nausicaa","Neaera","Nemerte","Nephele","Nesaea","Nicopolis","Nikaia","Nikasepolis","Niko","Niobe","Nysa","Oenone","Oitane","Olympias","Omphale","Oreithuia","Oreithyia","Orithyia","Orthia","Otonia","Pales","Panope","Panora","Parthenia","Parthenope","Pasiphae","Pelopia","Penelope","Penthesilea","Percalus","Perialla","Periboea","Pero","Perse","Persephone","Persis","Pervica","Pervinca","Phaedra","Phaedre","Phaethusa","Phaia","Pherenike","Pherusa","Phigaleia","Philea","Philinna","Philomache","Philomela","Philona","Phoebe","Phryne","Phylace","Phylia","Phyllis","Phylo","Phylomedusa","Podarge","Polycaste","Polydamna","Polydora","Polymede","Polyxena","Procne","Procris","Prone","Proto","Protogonia","Psamathe","Psyche","Pylia","Pyrrha","Pythias","Raisa","Rhea","Rhene","Rhoda","Rhode","Rhodope","Roxane","Sappho","Scylla","Sebasteia","Semele","Sophia","Sotera","Speio","Stheneboea","Stratonice","Tecmessa","Telephassa","Thais","Thalassa","Thaleia","Theano","Thebe","Thelma","Themis","Theodotis","Theophane","Theophania","Theophano","Theresa","Thessala","Thessalonike","Thetis","Thisbe","Thoë","Thoösa","Thyia","Timandra","Timo","Tryphena","Tryphosa","Tyro","Xanthe","Xanthippe","Xantippe","Xene","Xenophile","Zenobia","Zita","Zoe"],
    "romanMan":   ["Appius","Aulus","Caelus","Decius","Decimus","Faustus","Flavius","Gaius","Caius","Cnaeus","Gnaeus","Kaeso","Caeso","Lucius","Mamercus","Maximus","Manius","Marcus","Mettius","Numerius","Octavianus","Publius","Quintus","Secundus","Septimus","Servius","Sextus","Spurius","Tertius","Tiberius","Titus","Agrippa","Amulius","Arruns","Camillus","Canus","Cossus","Drusus","Gallus","Herius","Hostus","Lar","Lars","Marcellus","Nonus","Opiter","Oppius","Paulus","Paullus","Postumius","Potitus","Primus","Proclus","Proculus","Sisenna","Tullus","Vel","Vibius","Vopiscus","Amulius","Appius","Augustus","Aulus","Caius","Cassius","Decius","Flavius","Galerius","Gallio","Julianus","Kaeso","Lucius","Manius","Marcus","Numerius","Oppius","Placus","Publius","Quintis","Quintus","Secundus","Servius","Sextus","Spurius","Tertius","Tiberius","Titus"],
    "romanWoman": ["Aburia","Accia","Accoleia","Acilia","Aebutia","Aedinia","Aelia","Aemilia","Albania","Albatia","Allectia","Amatia","Annia","Antistia","Antia","Antonia","Appuleia","Aquillia","Armenia","Arria","Arsinia","Artoria","Asinia","Ateia","Atia","Atilia","Atria","Atronia","Attia","Aufidia","Aurelia","Auria","Ausonia","Avidia","Avita","Axia","Babudia","Baebia","Balventia","Bantia","Barbatia","Barria","Betiliena","Betucia","Blandia","Blossia","Bruccia","Bruttia","Bucculeia","Burriena","Caecilia","Caecina","Caecia","Caedicia","Caelia","Caeparia","Caepasia","Caerellia","Caesennia","Caesetia","Caesia","Caesonia","Caesulena","Caetronia","Calavia","Calidia","Calpurnia","Calventia","Calvisia","Camilia","Camillia","Camelia","Canidia","Caninia","Cania","Cantilia","Cantia","Canuleia","Canutia","Caprenia","Caria","Caristania","Carvilia","Cassia","Ceionia","Cicereia","Cilnia","Cincia","Cispia","Claudia","Clodia","Cloelia","Clovia","Cluilia","Cluntia","Cocceia","Coiedia","Cominia","Consentia","Considia","Coruncania","Cordia","Cornelia","Cosconia","Curia","Curtia","Decumia","Desticia","Dexsia","Didia","Dillia","Domitia","Dossenia","Duccia","Duronia","Egnatia","Epidia","Equitia","Fabia","Fadia","Faenia","Faleria","Favonia","Festinia","Flavia","Flavinia","Flavonia","Floridia","Floria","Floronia","Fufia","Fulcinia","Fulvia","Fundana","Furia","Gabinia","Galeria","Gavia","Gegania","Gellia","Grania","Gratia","Gratidia","Helvetia","Helvia","Herennia","Herminia","Hirtia","Horatia","Hortensia","Hosidia","Hostilia","Icilia","Insteia","Julia","Junia","Juventia","Laberia","Labiena","Laelia","Laetoria","Lafrenia","Lampronia","Lartia","Liburnia","Licinia","Livia","Lollia","Longinia","Loreia","Lucceia","Lucilia","Lucia","Lucretia","Lusia","Lutatia","Macrinia","Maecilia","Maelia","Mallia","Mamilia","Manlia","Manilia","Marcia","Maria","Matia","Maximia","Memmia","Menenia","Messiena","Metilia","Milonia","Minicia","Minucia","Modia","Mucia","Munatia","Munia","Murria","Naevia","Nasennia","Nemetoria","Nepia","Nigidia","Nigilia","Ninnia","Nipia","Norbana","Novia","Numeria","Octavia","Olcinia","Oppia","Opsia","Orania","Otacilia","Palpellia","Papinia","Papiria","Papia","Pedia","Peltrasia","Pescennia","Petellia","Petilia","Petillia","Petronia","Pinaria","Piscia","Pisentia","Placidia","Plautia","Plinia","Plotia","Pollia","Pompeia","Pompilia","Pomponia","Pomptina","Pontidia","Pontia","Popidia","Portia","Postumia","Potitia","Paesentia","Publicia","Pullo","Pupia","Quinctilia","Quinctia","Quirinia","Rabiria","Rufia","Rufria","Rusonia","Rutilia","Sabucia","Sallustia","Salonia","Salvia","Scribonia","Secundinia","Secundia","Seia","Sempronia","Sennia","Sentia","Septimia","Sepunia","Sepurcia","Sergia","Sertoria","Servilia","Sestia","Sextilia","Sextia","Sidonia","Silia","Sittia","Socellia","Sornatia","Spuria","Statia","Statilia","Stertinia","Suedia","Sulpicia","Tadia","Talmudia","Tanicia","Tertinia","Tettidia","Tettiena","Tettia","Titiedia","Titia","Titinia","Trebatia","Trebellia","Treblana","Tremellia","Tuccia","Tullia","Turullia","Ulpia","Umbrenia","Umbria","Ummidia","Urgulania","Uulia","Vagennia","Vagionia","Vagnia","Valeria","Varia","Vassenia","Vatinia","Vedia","Velia","Verania","Verecundia","Vergilia","Verginia","Vesnia","Vesuvia","Veturia","Vibenia","Vibidia","Vibia","Victricia","Viducia","Vinicia","Vipsania","Vipstana","Viridia","Viria","Visellia","Vitellia","Vitruvia","Volaginia","Volcatia","Volumnia","Volusenna","Volusena","Volusia","Vorenia"],
}

const NpcProfessions = [
    "Farmer",
    "Fisher",
    "Gamekeeper",
    "Hunter",
    "Lumberjack",
    "Miller",
    "Maid",
    "Miner",
    "Shepherd",
    "Stablehand",
    "Trapper",

    'Brickmaker',
    "Carpenter",
    "Stonemason",

    "Actor",
    "Musician",
    "Chef",
    "Dancer",
    "Gladiator",
    "Jester",
    "Painter",
    "Sculptor",
    "Singer",
    "Writer",

    "Banker",
    "Bookkeeper",
    "Grocer",
    "Guild Master",
    "Innkeeper",
    "Merchant",
    "Peddler",

    "Courier",
    "Town Crier",

    "Blacksmith ",
    "Fletcher",
    "Cobbler",
    "Leatherworker",
    "Jeweler",
    "Potter",
    "Tinker",

    "Assassin",
    "Bandit",
    "Crime Boss",
    "Pirate",
    "Poacher",
    "Smuggler",
    "Thief",

    "Diplomat",
    "Judge",
    "Knight",
    "Lawyer",
    "Master-of-Coin",
    "Noble",
    "Sheriff",
    "Squire",
    "Tax Collector",

    "Baker",
    "Barber",
    "Butcher",
    "Butler",
    "Cook",
    "Gardener",
    "Gravedigger",
    "Maid",
    "Porter",
    "Prostitute",
    "Servant",
    "Trainer",
    "Wet Nurse",

    "Artificer",
    "Bard",
    "Druid",
    "Healer",
    "Alchemist",
    "Mage",
    "Necromancer",
    "Sage",
    "Warlock",

    "Bodyguard",
    "Bouncer",
    "Captain",
    "Detective",
    "Executioner",
    "Firefighter",
    "Guard",
    "Jailer",
    "Medic",
    "Mercenary",
    "Quartermaster",
    "Sapper",
    "Scout",
    "Soldier",
    "Spy",

    "Bishop",
    "Cleric",
    "Cultist",
    "Inquisitor",
    "Missionary",
    "Monk",
    "Paladin",
    "Priest",

    "Apothecary",
    "Archivist",
    "Astrologer",
    "Doctor",
    "Engineer",
    "Herbalist",
    "Historian",
    "Librarian",
    "Mortician",
    "Nurse",
    "Professor",
    "Scholar",
    "Scribe",
    "Student",
    "Teacher",

    "Caravaneer",
    "Navigator",
    "Sailor",

    "Adventurer",
    "Beggar",
    "Bounty Hunter",
    "Drunkard",
    "Hermit",
    "Housewife",
    "Pilgrim",
    "Refugee",
    "Slave",
    "Urchin",
]

const NpcEmotions = {
    "Amusement": [
        "A shiny or rosy face",
        "Raised or wiggling eyebrows",
        "Snorting, laughing",
        "Chuckling or cackling",
        "Displaying a wide grin",
        "Exchanging knowing looks with others",
        "Witty commentary",
        "Making joking observations",
        "Turning away and bursting out in laughter",
        "A playful pinch, nudge, or shove",
        "Eyes squinting, lit with an inner glow or twinkle of mischief",
        "Smirking or offering a bemused smile"
    ],
    "Anger": [
        "Flaring nostrils",
        "Sweating",
        "Holding elbows wide from the body, chest thrust out",
        "Sweeping arm gestures",
        "Handling objects or people roughly",
        "A high chin",
        "Noisy breathing",
        "Legs that are planted wide",
        "Baring one's teeth",
        "Repetitive, sharp gestures (shaking a fist, etc.)",
        "Cutting people off when they speak"
    ],
    "Anxiety": [
        "Rubbing the back of the neck",
        "Crossing the arms, forming a barrier to others",
        "Standing with one arm holding the other at the elbow",
        "Clutching a purse, coat, or other object",
        "Wringing one's hands",
        "Twisting a watch or ring",
        "Scratching",
        "Hands repeatedly rising to touch one's face",
        "Fingering a necklace",
        "Rolling one's shoulders",
        "Bouncing a foot",
        "Glancing at the clock, phone, or doorway"
    ],
    "Concern": [
        "Eyebrows drawing together",
        "Tilting the head",
        "Strong eye contact",
        "One's mouth opening to speak, pausing to collect one's thoughts, then continuing",
        "An inward look and rapid blinking",
        "Moving closer, leaning in",
        "Growing still to better observe",
        "Making a micro-movement toward the object of concern, and then stopping",
        "Asking pointed questions to better understand the importance of what's unfolding",
        "Nodding and blinking as someone explains in more detail",
        "Eyebrows raising, lips pursing",
        "Entering the personal space of the person who is one's focus"
    ],
    "Confusion": [
        "Difficulty completing a task",
        "Fumbling",
        "Using um and uh hesitations",
        "Grimacing",
        "Excessive swallowing",
        "Scratching at one's cheek or temple",
        "Rubbing the chin",
        "Repeating back what was said as a question",
        "Touching the base of the neck",
        "Showing one's palms and shrugging",
        "An uncertain tone",
        "Increased difficulty in finding the right words"
    ],
    "Defensiveness": [
        "Stepping back",
        "Leaning away",
        "Crossing the arms over one's chest",
        "Rigid body posture",
        "Squinting eyes",
        "A lowering brow",
        "Sucking the cheeks in",
        "Shaking the head",
        "Sputtering, gaping",
        "Holding an object as a shield (a book, a folded jacket)",
        "A darting gaze",
        "Licking one's lips"
    ],
    "Depressed": [
        "A gaunt appearance",
        "Notable weight loss or gain",
        "Eyes that blink infrequently",
        "Wet or red eyes",
        "Staring down at one's hands",
        "Becoming non-reactive to stimulus or noise",
        "Laying in bed with no motivation to get up",
        "Saggy posture, bent neck",
        "Head resting on one's hand",
        "Tangled hair, overlong nails, and other signs of letting oneself go",
        "Wearing the same clothes day after day",
        "Shuffling steps"
    ],
    "Despair": [
        "Shoulders dragging, with the arms losing all strength",
        "A caved-in chest",
        "A slack expression",
        "A hanging head",
        "Letting out a hard sigh and closing one's eyes",
        "Eyebrows that pinch together",
        "A pained expression",
        "Slumping where one stands or sits",
        "Weakly throwing up one's hands",
        "Hands that slide loosely into one's lap",
        "Leaning forward, with the hands draping limply over one's knees",
        "Taking shallow yet audible breaths"
    ],
    "Doubt": [
        "Brows drawing closer, face tightening",
        "Looking down or away",+
        "Avoiding eye contact",
        "Pressing the lips together",
        "Shuffling one's feet",
        "Shoving hands in pockets",
        "Throat clearing",
        "Thumbing the ear",
        "Expressing concern",
        "Checking and rechecking one's appearance",
        "Delaying tactics (suggesting time to review options, etc.)"
    ],
    "Dread": [
        "Holding the stomach as if pained",
        "Clutching arms to one's chest",
        "Shoulders curling forward, caving the chest in",
        "A bent neck",
        "Leaning back or away from the source of discomfort",
        "Dragging footsteps",
        "Making excuses to leave",
        "A quiet voice, offering one-word responses",
        "Hunched posture and a drooping head",
        "Clasping one's knees tightly together",
        "Avoiding eye contact",
        "Turning the torso, shielding it"
    ],
    "Embarrassment": [
        "A flush that creeps across the cheeks",
        "Visible sweating",
        "The body freezing in place",
        "Grimacing or swallowing",
        "Ears that turn red",
        "The chin dipping down",
        "The chest caving",
        "A bent spine",
        "Hands curling around one's middle",
        "Feet shuffling",
        "Clearing the throat",
        "Coughing"
    ],
    "Excitement": [
        "A wide grin",
        "Eyes that sparkle and gleam",
        "Laughing",
        "Bouncing from foot to foot",
        "Squealing, hooting, yelling",
        "Telling jokes",
        "Chest bumping with others",
        "A loud voice",
        "Singing, humming, chanting",
        "Slam-dunking trash into a barrel after a game or event",
        "Babbling or talking over one another in a group setting",
        "Fanning oneself",
        "Pretending to faint",
        "Verbalizing thoughts and feelings without hesitation",
        "Lifting someone up or swinging them around",
        "Trembling",
        "Acting hyper, immature, or foolish out of a sense of fun",
        "A ruddy complexion",
        "Moving about, being unable to stay still",
        "Good-natured shoving and pushing",
        "Waving the arms, using grand gestures",
        "Drumming one's feet against the floor",
        "Hugging, grabbing onto someone's arm and holding it",
        "Bumping shoulders",
        "Raising up or bouncing on tiptoe",
        "Phoning or texting to share news or pass on the excitement",
        "Speed-talking with others, heads close together, gossipy",
        "Throaty laughter",
        "Getting the giggles",
        "Friendly demands such as 'Tell me!' or 'Let's go!'",
        "A body that's constantly in motion (nodding, bobbing, weaving, pacing)",
        "A distinct walk, a fast-paced strut",
        "Making eye contact with others, confidence",
        "Displaying affection with friends or loved ones"
    ],
    "Fear": [
        "Face turning ashen, white, pallid",
        "Hair lifting on the nape and arms",
        "Body odor, cold sweats",
        "Clammy hands",
        "Trembling lips and chin",
        "Tendons standing out in the neck, a visible pulse",
        "Elbows pressing into the sides, making one's body as small as possible",
        "Freezing, feeling rooted to the spot",
        "Rapid blinking",
        "Tight shoulders",
        "Staring but not seeing, eyes shut or crying",
        "Hands jammed into armpits or self-hugging",
        "Breath bursting in and out",
        "Leg muscles tightening, the body ready to run",
        "Looking all around, especially behind",
        "A shrill voice",
        "Lowering the voice to a whisper",
        "Keeping one's back to a wall or corner",
        "Shaking uncontrollably",
        "Gripping something, knuckles going white",
        "Stiff walking, the knees locking",
        "Beads of sweat on the lip or forehead",
        "Grabbing onto someone",
        "Eyes appearing damp and overly bright",
        "Stuttering and mispronouncing words, tremors in the voice",
        "Jerky movements, squirming",
        "Licking the lips, gulping down water",
        "Sprinting or running",
        "Sweeping a hand across the forehead to get rid of sweat",
        "Gasping and expelling one's breath as if pained",
        "Uncontrollable whimpering",
        "Pleading, talking to oneself",
        "Flinching at noises"
    ],
    "Grief": [
        "Shaky hands",
        "A vacant look; slack facial expressions",
        "A sudden loss of breath or struggling to find one's breath",
        "Dizziness or nausea",
        "Rubbing at one's chest",
        "Lashing out at others",
        "A loss of appetite",
        "Refusing to eat",
        "Frequent swallowing",
        "Lips that tremble and press together",
        "Holding or wearing a cherished item or gift belonging to the one who died",
        "Forgetting to change clothing or attend to one's hygiene"
    ],
    "Guilt": [
        "Averting or lowering one's gaze",
        "Turning away",
        "Shifting about",
        "Chin dipping to the chest, adopting a slumped posture",
        "Blushing",
        "Reacting defensively",
        "Short-temperedness",
        "Consuming antacids",
        "Repetitive swallowing",
        "Lying",
        "Sweating",
        "Grimacing"
    ],
    "Happiness": [
        "An upturned face",
        "Smiling",
        "Humming, whistling, singing",
        "A relaxed appearance",
        "Telling jokes, laughing frequently",
        "Laugh lines",
        "Raised, prominent cheekbones (from smiling)",
        "Eyes that dance, sparkle, or shine",
        "A bubbly or light voice",
        "Rapid speaking",
        "Buying gifts for others or offering tokens of kindness",
        "Stretching out the legs, adopting a wide, open stance"
    ],
    "Hatred": [
        "Fists that shake",
        "An intense, fevered stare",
        "Clenched jaw, grinding teeth",
        "Rigid and defined forearm muscles",
        "Uttering dark, hurtful words meant to provoke",
        "Stiff posture, square shoulders, a lurching walk",
        "Shoving, pushing, tripping",
        "Bearing the teeth",
        "Fingers retracting, turning claw-like",
        "Shouting, screaming, swearing",
        "Lunging at an enemy",
        "Spittle flying while yelling",
        "A red face and neck",
        "Sweating",
        "Visible vein throb",
        "A corded neck",
        "Walking off, refusing to stay in another's presence",
        "Switching shifts or altering a schedule to avoid an enemy",
        "Tightness in the face, skin stretched into a snarl",
        "An animalistic growl in the throat",
        "Flaring nostrils",
        "A grip that unintentionally crushes or breaks (snapping a pen, etc.)",
        "A tense body, on the verge of springing",
        "Bullying, cyber trolling",
        "A mouth that curls with dislike, sneering",
        "Spitting at someone or in their direction",
        "Reaching out to throttle, hit, or cause pain",
        "Shoving people aside to reach the enemy",
        "Angry tears",
        "Cursing, swearing",
        "A scathing tone",
        "A shaking voice",
        "Using friends to help ostracize or bring the enemy low",
        "Initiating hateful gossip, setting the enemy up, starting rumors",
        "Wrenching an enemy's arm to stop them from leaving",
        "Acting on violent urges (throwing a chair, destroying property)"
    ],
    "Humiliation": [
        "Body collapsing in on itself",
        "A bowed head",
        "Shoulders curling over chest",
        "Angling torso away from others",
        "Uncontrollable shuddering or shivering",
        "Hair hanging in face, hiding the eyes",
        "A downward gaze",
        "A flushed face",
        "Hitching chest",
        "Eyes dull, lifeless",
        "Pulling down a shirt hem (covering gesture)",
        "Body shielding (if holding onto an object)",
        "Hands clutching at stomach",
        "Covering face with hands",
        "Bottom lip or chin trembling",
        "Whimpering",
        "Throat bobbing",
        "Arms falling to sides, lifeless",
        "Uncontrolled tears",
        "Flinching at noise or from being touched",
        "Huddling, crouching",
        "Trying to cover body with hands",
        "Neck bending forward",
        "Movement is slow, jerky",
        "Knees locked tight together",
        "A loss of coordination",
        "Cold sweat",
        "Stumbling, staggering",
        "Backing up against a wall, sliding into a corner, hiding",
        "Visible tremors coursing through the body",
        "Hands gripping elbows",
        "Pigeon toes (tilted inward)",
        "Sobs trapped in throat",
        "Drawing knees up to the body's core",
        "Wrapping arms around self",
        "Runny nose",
    ],
    "Jealousy": [
        "Adopting a sullen look",
        "Making a slight growl or noise in the throat",
        "Bitterness at watching how others respond to the rival",
        "Quick, sharp movements (swiping tears from cheeks, shoving hair out of eyes)",
        "Pursing or pressing lips flat",
        "Crossing arms in front of chest",
        "Clenching teeth",
        "Muttering unkind things under breath",
        "Starting rumors, acting catty",
        "Picking on someone weaker for a sense of power and control"
    ],
    "Loneliness": [
        "A longing gaze",
        "Disinterest in one's appearance (bland clothing, lackluster hair)",
        "Slumped shoulders, limp posture",
        "A monotone voice",
        "Looking down when walking in public",
        "Watching people furtively",
        "An expressionless, unsmiling face",
        "Sullenness",
        "Being generous to others in order to curry favor",
        "Spying or eavesdropping on others to feel a part of something",
        "Filling schedule with work or volunteering to avoid downtime",
        "Using books, the internet, and TV to escape"
    ],
    "Obsessed": [
        "Listening with rapt attention (leaning forward, eyes wide, vigorously nodding the head, etc.)",
        "The pitch of one's voice rising",
        "An over-bright, fanatic shine in the eyes",
        "A laser-focused gaze",
        "An unkempt appearance (uncombed hair, wrinkled clothing, bags under the eyes, etc.)",
        "One's words running together as one talks about the obsession",
        "Speaking animatedly (flapping the hands, bouncing on the heels, fingers jittering, etc.)",
        "Monopolizing conversations; talking over other people to voice one's opinions"
    ],
    "Panic": [
        "Quick, shallow breathing",
        "Eyes that are wide, with white showing around the whole iris",
        "Hyperventilating",
        "Squeezing the eyes shut",
        "Clenching and unclenching the fists",
        "Folding the body over and making oneself small",
        "Rubbing at one's throat",
        "Veins standing out in one's neck",
        "Loosening a tie or unfastening collar buttons",
        "Involuntary moans or whimpers",
        "Being on edge (jumping at sounds, difficulty concentrating, etc.)"
    ],
    "Paranoia": [
        "Startling easily",
        "Clenching the jaw",
        "Darting eye movements",
        "Excessive safety precautions (extra locks, guard dogs, video surveillance)",
        "Fidgety hands that won't settle",
        "Wide eyes",
        "Restless sleep, tossing and turning",
        "Insomnia",
        "Backing away with raised hands",
        "Flinching",
        "Eyes that don't seem to blink often enough",
        "Crossing the arms tightly over the chest"
    ],
    "Pride": [
        "A high chin",
        "Shoulders back",
        "Chest thrust out",
        "Standing tall with good posture, legs spread wide",
        "A gleam in one's eye",
        "A knowing grin",
        "Perfectionism",
        "Watching others to see their reactions",
        "Verbalizing the ups and downs that led to this point",
        "Calling friends and loved ones to tell them about an accomplishment",
        "Direct or intense eye contact",
        "A booming laugh",
        "Becoming talkative",
        "Lifting the heels and rising up slightly to emphasize words",
        "Steering or dominating the conversation",
        "Becoming extra animated when there's an audience",
        "A grin that conveys secret knowledge",
        "Thrusting oneself into the middle of an event or debate",
        "A satisfied smile",
        "Hooking thumbs into one's belt loops, thrusting the pelvis forward",
        "Pulling in a deep breath",
        "False modesty",
        "Ignoring or overlooking any flaws associated with the pride item",
        "A preoccupation with one's appearance",
        "Standing with hands tucked in one's armpits, thumbs visible and pointing up",
        "Running the hands through the hair, flipping hair back",
        "Assuming a pose that's sexy or draws attention to one's best attributes",
        "Appearing unaffected by what others think",
        "Speaking first, thinking second"
    ],
    "Regret": [
        "Scrubbing a hand over the face",
        "Laying a hand against the breastbone",
        "A heavy sigh",
        "A downturned mouth",
        "Bent posture",
        "Heavy arms, the shoulders pulled low",
        "Apologizing",
        "Trying to reason or explain",
        "Eyebrows gathering in",
        "A pained expression",
        "Hands falling to the sides",
        "Staring down at one's feet"
    ],
    "Sadness": [
        "Crying",
        "Puffy face or eyes",
        "Eyes appear red",
        "Running makeup",
        "Splotchy skin",
        "Sniffing, wiping at nose",
        "Wincing",
        "Drooping shoulders",
        "Voice is tearful or breaks",
        "Staring down at one's hands",
        "Stooped posture",
        "Rubbing the heel of a palm against chest"
    ],
    "Suspicion": [
        "Narrowing the eyes, squinting",
        "Body angling away from suspect",
        "A wrinkled brow",
        "Flushed skin",
        "A deliberate lowering of the head to study or stare",
        "Arms tight to the body",
        "Shooting glances at the suspect",
        "Avoiding direct eye contact",
        "A fake smile",
        "Sneaking or spying",
        "Eavesdropping",
        "Following the suspected person"
    ],
}
const NpcBonds = [
    "I would die to recover an ancient artifact of my faith that was lost long ago.",
    "2. I will someday get revenge on the corrupt temple hierarchy who branded me a heretic.",
    "I owe me life to the priest who took me in when my parents died",
    "Everything I do is for the common people.",
    "I will do anything to protect the temple where I served.",
    "I seek to preserve a sacred text that my enemies consider heretical and seek to destroy.",
    "I fleeced the wrong person and must work to ensure that this individual never crosses paths with me or those I care about.",
    "I owe everything to my mentor--a horrible person who's probably rotting in jail somewhere.",
    "Somewhere out there I have a child who doesn't know me. I'm making the world better for him or her.",
    "I come from a noble family, and one day I'll reclaim my lands and title from those who stole them from me.",
    "A powerful person killed someone I love. Some day soon, I'll have my revenge.",
    "I swindled and ruined a person who didn't deserve it. I seek to atone for my misdeeds but might never be able to forgive myself.",
    "I'm trying to pay off an old debt I owe to a generous benefactor.",
    "My ill-gotten gains go to support my family.",
    "Something important was taken from me, and I aim to steal it back.",
    "I will become the greatest thief that ever lived.",
    "I'm guilty of a terrible crime. I hope I can redeem myself for it.",
    "Someone I loved died because of a mistake I made. That will never happen again.",
    "My instrument is my most treasured possession, and it reminds me of someone I love.",
    "Someone stole my precious instrument, and someday I'll get it back.",
    "I want to be famous, whatever it takes.",
    "I idolize a hero of the old tales and measure my deeds against that person's.",
    "I will do anything to prove myself superior to me hated rival.",
    "I would do anything for the other members of my old troupe.",
    "I have a family, but I have no idea where they are. One day, I hope to see them again.",
    "I worked the land, I love the land, and I will protect the land.",
    "A proud noble once gave me a horrible beating, and I will take my revenge on any bully I encounter.",
    "My tools are symbols of my past life, and I carry them so that I will never forget my roots.",
    "I protect those who cannot protect themselves.",
    "I wish my childhood sweetheart had come with me to pursue my destiny.",
    "The workshop where I learned my trade is the most important place in the world to me.",
    "I created a great work for someone, and then found them unworthy to receive it. I'm still looking for someone worthy.",
    "I owe my guild a great debt for forging me into the person I am today.",
    "I pursue wealth to secure someone's love.",
    "One day I will return to my guild and prove that I am the greatest artisan of them all.",
    "I will get revenge on the evil forces that destroyed my place of business and ruined my livelihood.",
    "Nothing is more important than the other members of my hermitage, order, or association.",
    "I entered seclusion to hide from the ones who might still be hunting me. I must someday confront them.",
    "I'm still seeking the enlightenment I pursued in my seclusion, and it still eludes me.",
    "I entered seclusion because I loved someone I could not have.",
    "Should my discovery come to light, it could bring ruin to the world.",
    "My isolation gave me great insight into a great evil that only I can destroy.",
    "I will face any challenge to win the approval of my family.",
    "My house's alliance with another noble family must be sustained at all costs.",
    "Nothing is more important that the other members of my family.",
    "I am in love with the heir of a family that my family despises.",
    "My loyalty to my sovereign is unwavering.",
    "The common folk must see me as a hero of the people.",
    "My family, clan, or tribe is the most important thing in my life, even when they are far from me.",
    "An injury to the unspoiled wilderness of my home is an injury to me.",
    "I will bring terrible wrath down on the evildoers who destroyed my homeland.",
    "I am the last of my tribe, and it is up to me to ensure their names enter legend.",
    "I suffer awful visions of a coming disaster and will do anything to prevent it.",
    "It is my duty to provide children to sustain my tribe.",
    "It is my duty to protect my students.",
    "I have an ancient text that holds terrible secrets that must not fall into the wrong hands.",
    "I work to preserve a library, university, scriptorium, or monastery.",
    "My life's work is a series of tomes related to a specific field of lore.",
    "I've been searching my whole life for the answer to a certain question.",
    "I sold my soul for knowledge. I hope to do great deeds and win it back.",
    "I'm loyal to my captain first, everything else second.",
    "The ship is most important--crewmates and captains come and go.",
    "I'll always remember my first ship.",
    "In a harbor town, I have a paramour whose eyes nearly stole me from the sea.",
    "I was cheated of my fair share of the profits, and I want to get my due.",
    "Ruthless pirates murdered my captain and crewmates, plundered our ship, and left me to die. Vengeance will be mine.",
    "I would lay down my life for the people I served with.",
    "Someone saved my life on the battlefield. To this day, I will never leave a friend behind.",
    "My honor is my life.",
    "I'll never forget the crushing defeat my company suffered or the enemies who dealt it.",
    "Those who fight beside me are those worth dying for.",
    "I fight for those who cannot fight for themselves.",
    "My town or city is my home, and I'll fight to defend it.",
    "I sponsor an orphanage to keep others from enduring what I was forced to endure.",
    "I owe my survival to another urchin who taught me to live on the streets.",
    "I owe a debt I can never repay to the person who took pity on me.",
    "I escaped my life of poverty by robbing an important person, and I'm wanted for it.",
    "No one else is going to have to endure the hardships I've been through."
]

export {NpcNames};
export {NpcProfessions};
export {NpcEmotions};
export {NpcBonds};
